apiVersion: apps/v1
kind: Deployment
namespace: k8s-appsody
metadata:
  name: che-emulator
spec:
  selector:
    matchLabels:
      app: appsody
  replicas: 1
  template:
    metadata:
      labels:
        app: appsody
    spec:
      serviceAccountName: appsody-sa
      containers:
      - name: appsody-init
        securityContext: 
          privileged: true
        runAsUser: 0
        image: chilantim/my-buildah
        imagePullPolicy: Always
        command: ['/bin/sh']
        args: ['-c', '/tmp/appsody-setup.sh']
        workingDir: /workspace
        volumeMounts:
          - name: appsody-controller
            mountPath: /.appsody
          - name: appsody-workspace
            mountPath: /workspace
          - name: buildah-containers
            mountPath: /var/lib/containers
      volumes:
        - name: appsody-controller
          persistentVolumeClaim: 
            claimName: appsody-controller
        - name: appsody-workspace
          persistentVolumeClaim: 
            claimName: appsody-workspace
        - name: buildah-containers
          emptyDir: {}
