apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsody-controller
spec:
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/docker-volume
